spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop?serverTimezone=Asia/Seoul
    username: root
    password: 12345678

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092